name: CI
on:
  push:
    branches:
    - 'master'
  pull_request:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18, 20]
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 1

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - run: yarn
      - run: yarn format:check
      - run: yarn lint
      - run: yarn build
      - run: yarn test --collect-coverage

      - name: Repo is clean after all the steps
        run: git diff --quiet --exit-code
